name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  lint-build-test:
    name: Lint, Test, Assemble

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      - name: Run Android Linter
        run: ./gradlew lintStagingDebug

      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest

      - name: Assemble Debug APK
        run: ./gradlew assembleStagingDebug
